name: Fragments
favicon: null
layout_spectrum: 0.8726711871568114
typography_spectrum: 0.23296161298640072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4355562508571893
  lightness: 0.9742437803652138
  saturation: 0.7240680705290288
  rhythmicContrast: 0.07088230364024639
purpose: []
