name: Fragments
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2509
title: Life in My Head
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#849ab1'
    - '#0f0f11'
    - '#ffffff'
    - '#3a3c49'
    - '#ffb375'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
